# Generated by Django 5.0.2 on 2024-03-01 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name_plural": "cities"},
        ),
        migrations.AlterModelOptions(
            name="property",
            options={"verbose_name_plural": "properties"},
        ),
        migrations.AddField(
            model_name="property",
            name="city",
            field=models.ForeignKey(
                default="fac177eb-1453-47d8-9b0f-254506b30198",
                on_delete=django.db.models.deletion.CASCADE,
                to="properties.city",
            ),
            preserve_default=False,
        ),
    ]
